name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the Terraform workspace'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 'Terraform Init'
        working-directory: infra
        run: terraform init
        
      - name: 'Set workspace or create if not exists'
        working-directory: infra
        run: terraform workspace select ${{ inputs.environment }}  || terraform workspace new ${{ inputs.environment }} 
        
      - name: 'Terraform Validate'
        working-directory: infra
        run: terraform validate
        
      - name: 'Terraform Plan -destroy'
        working-directory: infra
        run: terraform plan -destroy

      - name: 'Terraform Destroy'
        working-directory: infra
        run: terraform destroy -auto-approve